### ISSUE TITLE
本地运行，貌似前台注册，会失败，我数据库8.0，接口/api-client/v1/sign-up

### ISSUE THREAD

**Issue by dingfeipeng** [maoxiaoquan/kite#12]
本地运行，貌似前台注册，会失败，我数据库8.0，接口/api-client/v1/sign-up， {"state":"error","message":"错误信息：You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc LIMIT 1' at line 1","data":{}}

**Comment by maoxiaoquan** [comment]
你好，周一会发布新版本，修复问题

**Comment by maoxiaoquan** [comment]
你好，已修复，请查看是否还存在

**Comment by dingfeipeng** [comment]
好的，我测试下
