### ISSUE TITLE
错误提示:当前功能用户无权限或者当前用户已被网站管理员禁用此功能，请联系管理员开启!

### ISSUE THREAD

**Issue by CatciSurn** [maoxiaoquan/kite#20]
如题所示
# 说明
我在点击发布文章按钮时出现了这样一个信息弹窗，但我在后台并没有找到这样一个选项，请问这是默认关闭的吗

**Comment by CatciSurn** [comment]
# 问题已经解决
在后台设置角色时，只有在都设置 官方管理团队 和 默认用户 两个标签，才能拥有管理员权限

**Comment by maoxiaoquan** [comment]
你可以给角色编辑权限，只要一个也可以
