### ISSUE TITLE
请问注册发送验证码时报错550是什么原因

### ISSUE THREAD

**Issue by 9mhz** [maoxiaoquan/kite#25]
![image](https://user-images.githubusercontent.com/64386741/112920560-c9d1cd00-913b-11eb-9fd5-a235d7191883.png)

**Comment by maoxiaoquan** [comment]
你好，邮件归档了，导致我没能收到邮件，真的十分抱歉，我才看到


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maoxiaoquan/kite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 上午10:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [maoxiaoquan/kite] 请问注册发送验证码时报错550是什么原因 (#25)





 
Closed #25.
