### ISSUE TITLE
大佬 数据库名 数据库密码啥的 要填什么?

### ISSUE THREAD

**Issue by ghost** [maoxiaoquan/kite#3]

**Comment by maoxiaoquan** [comment]
数据库用的是mysql , 你下一个 phpstudy ，然后建一个数据库，默认的账户密码都是root，今天下午晚点，我在网站贴一个详细的教程出来

**Comment by ghost** [comment]
x谢谢大佬

**Comment by afacode** [comment]
自己建一个数据库，在 `server/config/index.js`  里面的 database 直接写死，或者在寻找 应该在`db/lowdb/db.json` mysql 增加， 运行前先应该要`npm run mysql`建表， 建表时，在代码修改
`db/mysqldb/index.js` 多exports 一个 `sequelize`  在 `create.js ` 修改代码 
`models.sequelize.sync({
  force: true
}).then(() => {
  console.log('数据表创建成功')
})`

**Comment by maoxiaoquan** [comment]
https://www.xiaosuibi.com/p/10007 

安装的教程

目前还有一些不完善的地方，
初始化里面的代码主要是为了实现功能，所以代码有些不美观，但是功能是没问题的，

**Comment by maoxiaoquan** [comment]
按照这个来吧，初始化里面有一些权限的初始化，暂时还不能略过，有什么问题，在这里提就可以，

**Comment by maoxiaoquan** [comment]
接下来，主要改一些未发现的bug，然后优化代码，

**Comment by 9668596818ez** [comment]
> https://www.xiaosuibi.com/p/10007
> 
> 安装的教程
> 
> 目前还有一些不完善的地方，
> 初始化里面的代码主要是为了实现功能，所以代码有些不美观，但是功能是没问题的，

**Comment by ghost** [comment]
跑起来了  谢谢
