### ISSUE TITLE
关于使用sync问题

### ISSUE THREAD

**Issue by moshuchao** [maoxiaoquan/kite#4]
```
models.admin_user.sync({
  force: true
}).then(() => {
  console.log('所有数据表创建完成')
})
```
设置`force:true`，数据丢失不会有问题吗？

**Comment by maoxiaoquan** [comment]
models_type/models_type/create.js 
这个文件是预留给开发时，表有变动，变更用的，里面的字段可以随便写
如果用不到，直接忽略这个

初始化按照我写的那个教程来就可以

https://www.xiaosuibi.com/p/10007

**Comment by maoxiaoquan** [comment]
这个文件，我等下里面留个备注，不然总被误解了

**Comment by maoxiaoquan** [comment]
比如说，开发前没有admin_user这个表，我需要新增，就可以在这里面写了，这个是预留的一个文件
