### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tangka** [maoxiaoquan/kite#8]
Error: Cannot find module '../../static/_client/vue-ssr-server-bundle.json'

**Comment by tangka** [comment]
运行dev1.1报的错，是不是还需要什么环境

**Comment by tangka** [comment]
kite-beta-0.1可以，其他的都有，是不是webpack环境问题

**Comment by maoxiaoquan** [comment]
先运行下npm run client-build ，我忽略了打包生成的文件，怕太大了
