### ISSUE TITLE
在npm run init时，创建超级管理员那一步报错

### ISSUE THREAD

**Issue by SZ98** [maoxiaoquan/kite#9]
错误信息：Incorrect string value: '\xE6\x96\x87\xE7\xAB\xA0...' for column 'authority_name' at row 1

![image](https://user-images.githubusercontent.com/18752143/66536056-4a6acb00-eb4e-11e9-924b-64b8cd7fef61.png)

**Comment by maoxiaoquan** [comment]
你好，你使用的是哪个分支？
开发平台是？

**Comment by SZ98** [comment]
您好，master分支，webstorm

**Comment by maoxiaoquan** [comment]
你好，我判断可能是你创建数据库的时候，数据库的类型不是 
![image](https://user-images.githubusercontent.com/15361672/66536435-87838d00-eb4f-11e9-8e80-65a187bbc8d3.png)

所以无法存储中文，你重新更改下试下

**Comment by SZ98** [comment]
是的，创建了再修改没修改过来，删库重新在创建的时候设置了就好了，非常感谢

**Comment by maoxiaoquan** [comment]
哈哈，好的，互相学习
